app:
  name: managementSystemTemplate

  # MySQL
  mysql:
    host: 192.168.11.8
    port: 3306
    db: management_template
    username: root
    password: 123456

  # Redis
  redis:
    host: 192.168.11.8
    port: 6379
    db: 11
    password: 123456